customhost = "imtelliproject.copp4pnf6x05.ap-south-1.rds.amazonaws.com"
customuser = "intelliadmin"
custompass = "intelliproject"
customdb = "employee"
custombucket = "intelliemploy"
customregion = "ap-south-1"
